// ============================================================================
//  GST PDF / print engine — A4, branded, print-ready.
//  e-Invoice PDF (IRN + Ack + QR + tax & HSN summary) and EWB PDF (Part A/B,
//  validity, vehicle, transporter, QR). pdfkit + qrcode.
//  Buffers are returned so routes can stream, download or attach them.
// ============================================================================

import fs from 'node:fs';
import path from 'node:path';
import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import { company } from '../../config/company.js';
import { STATE_CODES } from './masterData.js';
import { UPLOAD_ROOT } from '../../middleware/upload.js';

// Resolve a branding image file (logo/signature/stamp) if it exists.
function brandFile(branding, key) {
  const name = branding?.[key];
  if (!name) return null;
  const p = path.join(UPLOAD_ROOT, name);
  return fs.existsSync(p) ? p : null;
}

// Faint diagonal watermark across the page.
function watermark(doc, text) {
  if (!text) return;
  const sx = doc.x, sy = doc.y;
  doc.save();
  doc.rotate(-45, { origin: [doc.page.width / 2, doc.page.height / 2] });
  doc.fontSize(64).fillColor('#1d4ed8').fillOpacity(0.06)
    .text(String(text).toUpperCase(), 0, doc.page.height / 2 - 40, { width: doc.page.width, align: 'center', lineBreak: false });
  doc.fillOpacity(1).restore();
  doc.x = sx; doc.y = sy; // never let the watermark advance the text cursor / add pages
}

const BRAND = '#1d4ed8';
const INK = '#0f172a';
const MUTE = '#64748b';
const LINE = '#e2e8f0';

const inr = (v) => '₹' + Number(v || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const st = (c) => STATE_CODES[String(c || '').padStart(2, '0')] || c || '';
const dmy = (d) => {
  if (!d) return '—';
  const t = new Date(d);
  if (Number.isNaN(t.getTime())) return String(d);
  return `${String(t.getDate()).padStart(2, '0')}/${String(t.getMonth() + 1).padStart(2, '0')}/${t.getFullYear()}`;
};

function toBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

function header(doc, title, subtitle, branding = {}) {
  doc.rect(0, 0, doc.page.width, 70).fill(BRAND);
  const logo = brandFile(branding, 'logoFile');
  let tx = 40;
  if (logo) { try { doc.image(logo, 40, 14, { height: 42, width: 42, fit: [42, 42] }); tx = 92; } catch { /* bad image */ } }
  doc.fillColor('#ffffff').fontSize(16).font('Helvetica-Bold').text(branding.headerText || company.pdfName, tx, 18, { lineBreak: false });
  doc.fontSize(8).font('Helvetica').fillColor('#dbeafe')
    .text(`${company.address}`, tx, 38)
    .text(`GSTIN: ${company.gstin}  •  CIN: ${company.cin}  •  ${branding.contactInfo || company.email}`, tx, 50);
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(13).text(title, 40, 18, { width: doc.page.width - 80, align: 'right' });
  if (subtitle) doc.fontSize(8).font('Helvetica').fillColor('#dbeafe').text(subtitle, 40, 38, { width: doc.page.width - 80, align: 'right' });
  doc.fillColor(INK);
  doc.y = 86;
}

function footer(doc, note, branding = {}) {
  const y = doc.page.height - 52;
  doc.moveTo(40, y).lineTo(doc.page.width - 40, y).strokeColor(LINE).lineWidth(1).stroke();
  doc.fontSize(7).fillColor(MUTE).font('Helvetica');
  if (note) doc.text(note, 40, y + 5, { width: doc.page.width - 80, align: 'center' });
  doc.text(branding.footerText || 'This is a computer-generated document. Generated by the ARRAYS INGENIERIA GST Compliance engine.', 40, y + (note ? 14 : 5), { width: doc.page.width - 80, align: 'center' });
  if (branding.disclaimer) doc.fontSize(6).text(branding.disclaimer, 40, y + (note ? 24 : 15), { width: doc.page.width - 80, align: 'center' });
}

// Bottom limit for flowing content (footer space reserved below this).
const CONTENT_BOTTOM = (doc) => doc.page.height - 64;

// Compact header for continuation pages (pages 2+).
function contHeader(doc, branding, title) {
  doc.rect(0, 0, doc.page.width, 30).fill(BRAND);
  doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold').text(branding.headerText || company.pdfName, 40, 9, { lineBreak: false });
  doc.font('Helvetica').fontSize(9).text(`${title} (continued)`, 40, 9, { width: doc.page.width - 80, align: 'right' });
  doc.fillColor(INK);
  return 40;
}

// Draw footer + page numbers on EVERY buffered page (called once at the end).
function finalize(doc, note, branding = {}) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    const y = doc.page.height - 52;
    doc.moveTo(40, y).lineTo(doc.page.width - 40, y).strokeColor(LINE).lineWidth(1).stroke();
    doc.fontSize(7).fillColor(MUTE).font('Helvetica');
    if (note) doc.text(note, 40, y + 4, { width: doc.page.width - 80, align: 'center' });
    doc.text(branding.footerText || 'This is a computer-generated document. Generated by the ARRAYS INGENIERIA GST Compliance engine.', 40, y + (note ? 13 : 4), { width: doc.page.width - 80, align: 'center' });
    if (branding.disclaimer) doc.fontSize(6).text(branding.disclaimer, 40, y + (note ? 22 : 13), { width: doc.page.width - 80, align: 'center' });
    doc.fontSize(7).fillColor(MUTE).text(`Page ${i + 1} of ${range.count}`, doc.page.width - 110, y + 3, { width: 70, align: 'right' });
  }
  doc.flushPages();
}

function box(doc, x, y, w, h, fill) {
  doc.roundedRect(x, y, w, h, 4).lineWidth(1).strokeColor(LINE);
  if (fill) doc.fillAndStroke(fill, LINE); else doc.stroke();
  doc.fillColor(INK);
}

function partyBlock(doc, x, y, w, label, p = {}) {
  box(doc, x, y, w, 92, '#f8fafc');
  doc.fontSize(8).fillColor(BRAND).font('Helvetica-Bold').text(label, x + 8, y + 6);
  doc.fillColor(INK).fontSize(9).font('Helvetica-Bold').text(p.legalName || p.tradeName || '—', x + 8, y + 18, { width: w - 16 });
  doc.font('Helvetica').fontSize(8).fillColor(MUTE);
  const lines = [
    p.gstin ? `GSTIN: ${p.gstin}` : null,
    [p.addr1, p.addr2].filter(Boolean).join(', '),
    [p.location, p.pincode].filter(Boolean).join(' - '),
    p.stateCode ? `State: ${st(p.stateCode)} (${String(p.stateCode).padStart(2, '0')})` : null,
    p.phone ? `Ph: ${p.phone}` : null,
  ].filter(Boolean);
  doc.text(lines.join('\n'), x + 8, y + 32, { width: w - 16, lineGap: 1 });
  doc.fillColor(INK);
}

// ── e-INVOICE PDF ───────────────────────────────────────────────────────────
export async function einvoicePdf(rec, branding = {}) {
  const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
  const out = toBuffer(doc);
  const W = doc.page.width;

  header(doc, rec.docType === 'CRN' ? 'CREDIT NOTE (e-Invoice)' : rec.docType === 'DBN' ? 'DEBIT NOTE (e-Invoice)' : 'TAX INVOICE (e-Invoice)',
    rec.irn ? 'IRN Registered' : 'Not yet registered', branding);
  watermark(doc, branding.watermark || (rec.isCancelled ? 'CANCELLED' : (rec.irn ? '' : 'DRAFT')));

  // IRN / Ack / QR strip
  const stripY = doc.y;
  box(doc, 40, stripY, W - 200, 70, '#eff6ff');
  doc.fontSize(7).fillColor(MUTE).font('Helvetica-Bold').text('IRN', 48, stripY + 7);
  doc.fontSize(7.5).fillColor(INK).font('Courier').text(rec.irn || '— pending —', 48, stripY + 17, { width: W - 220 });
  doc.font('Helvetica').fontSize(7).fillColor(MUTE)
    .text(`Ack No: `, 48, stripY + 40, { continued: true }).fillColor(INK).text(rec.ackNo || '—')
    .fillColor(MUTE).text(`Ack Date: `, 220, stripY + 40, { continued: true }).fillColor(INK).text(rec.ackDate ? dmy(rec.ackDate) : '—');

  // QR
  if (rec.signedQr) {
    try {
      const png = await QRCode.toBuffer(String(rec.signedQr).slice(0, 1200), { margin: 0, width: 150 });
      box(doc, W - 150, stripY, 110, 70, '#ffffff');
      doc.image(png, W - 145, stripY + 5, { width: 60, height: 60 });
      doc.fontSize(6).fillColor(MUTE).text('Signed QR', W - 80, stripY + 28, { width: 38 });
    } catch { /* ignore QR failure */ }
  }
  doc.y = stripY + 80;

  // Doc meta
  const my = doc.y;
  box(doc, 40, my, W - 80, 24, '#f8fafc');
  doc.fontSize(8).fillColor(INK).font('Helvetica-Bold')
    .text(`Invoice No: ${rec.docNo || '—'}`, 48, my + 8, { continued: true }).font('Helvetica')
    .text(`     Date: ${dmy(rec.docDate)}     Supply: ${rec.supplyType || '—'}     Reverse Charge: ${rec.reverseCharge ? 'Yes' : 'No'}`);
  doc.y = my + 32;

  // Parties
  const py = doc.y;
  partyBlock(doc, 40, py, (W - 90) / 2, 'SUPPLIER', rec.seller);
  partyBlock(doc, 40 + (W - 90) / 2 + 10, py, (W - 90) / 2, 'RECIPIENT', { ...rec.buyer, stateCode: rec.buyer?.stateCode || rec.buyer?.pos });
  doc.y = py + 100;

  // Items table
  const cols = [
    { k: 'slNo', t: '#', w: 22, a: 'left' },
    { k: 'description', t: 'Description', w: 150, a: 'left' },
    { k: 'hsn', t: 'HSN', w: 48, a: 'left' },
    { k: 'quantity', t: 'Qty', w: 38, a: 'right' },
    { k: 'unitPrice', t: 'Rate', w: 55, a: 'right' },
    { k: 'taxableValue', t: 'Taxable', w: 62, a: 'right' },
    { k: 'gstRate', t: 'GST%', w: 34, a: 'right' },
    { k: 'tax', t: 'Tax', w: 55, a: 'right' },
    { k: 'totalItemValue', t: 'Total', w: 61, a: 'right' },
  ];
  const x0 = 40;
  const wm = branding.watermark || (rec.isCancelled ? 'CANCELLED' : (rec.irn ? '' : 'DRAFT'));
  const drawHead = (ty) => {
    doc.rect(40, ty, W - 80, 18).fill(BRAND);
    let cx = x0 + 4;
    doc.fillColor('#fff').fontSize(7.5).font('Helvetica-Bold');
    cols.forEach((c) => { doc.text(c.t, cx, ty + 5, { width: c.w - 4, align: c.a }); cx += c.w; });
    doc.font('Helvetica').fillColor(INK).fontSize(7.5);
    return ty + 18;
  };
  let ty = drawHead(doc.y);
  const rowH = 16;
  (rec.items || []).forEach((it, i) => {
    if (ty + rowH > CONTENT_BOTTOM(doc)) { doc.addPage(); watermark(doc, wm); ty = drawHead(contHeader(doc, branding, 'TAX INVOICE')); }
    const tax = Number(it.igstAmount || 0) + Number(it.cgstAmount || 0) + Number(it.sgstAmount || 0);
    if (i % 2) { doc.rect(40, ty, W - 80, rowH).fill('#f8fafc'); doc.fillColor(INK); }
    let cx = x0 + 4;
    cols.forEach((c) => {
      let v = it[c.k];
      if (c.k === 'slNo') v = it.slNo || i + 1;
      else if (c.k === 'tax') v = inr(tax);
      else if (['unitPrice', 'taxableValue', 'totalItemValue'].includes(c.k)) v = inr(v);
      else if (c.k === 'gstRate') v = `${Number(v || 0)}%`;
      doc.text(String(v ?? ''), cx, ty + 4, { width: c.w - 4, align: c.a, ellipsis: true });
      cx += c.w;
    });
    ty += rowH;
  });
  doc.rect(40, ty, W - 80, 0).strokeColor(LINE).stroke();
  doc.y = ty + 8;

  // Keep the totals + declaration block together — move to a new page if needed.
  if (doc.y + 150 > CONTENT_BOTTOM(doc)) { doc.addPage(); watermark(doc, wm); doc.y = contHeader(doc, branding, 'TAX INVOICE'); }

  // Tax summary box (right)
  const v = rec.val || {};
  const sumX = W - 250; let sy = doc.y;
  box(doc, sumX, sy, 210, 110, '#f8fafc');
  const rowsSum = [
    ['Assessable Value', v.assessableValue], ['CGST', v.cgstValue], ['SGST', v.sgstValue],
    ['IGST', v.igstValue], ['Cess', v.cessValue], ['Round Off', v.roundOff],
  ];
  doc.fontSize(8).font('Helvetica');
  rowsSum.forEach((r, i) => {
    doc.fillColor(MUTE).text(r[0], sumX + 8, sy + 8 + i * 13);
    doc.fillColor(INK).text(inr(r[1]), sumX + 8, sy + 8 + i * 13, { width: 194, align: 'right' });
  });
  doc.moveTo(sumX + 6, sy + 92).lineTo(sumX + 204, sy + 92).strokeColor(LINE).stroke();
  doc.font('Helvetica-Bold').fontSize(10).fillColor(BRAND)
    .text('Total Invoice Value', sumX + 8, sy + 95)
    .text(inr(v.totalInvoiceValue), sumX + 8, sy + 95, { width: 194, align: 'right' });

  // HSN summary (left)
  const hsnMap = {};
  (rec.items || []).forEach((it) => {
    const k = it.hsn || '—';
    hsnMap[k] = hsnMap[k] || { taxable: 0, tax: 0 };
    hsnMap[k].taxable += Number(it.taxableValue || 0);
    hsnMap[k].tax += Number(it.igstAmount || 0) + Number(it.cgstAmount || 0) + Number(it.sgstAmount || 0);
  });
  doc.font('Helvetica-Bold').fontSize(8).fillColor(BRAND).text('HSN Summary', 40, sy);
  doc.font('Helvetica').fontSize(7.5).fillColor(INK);
  let hy = sy + 14;
  Object.entries(hsnMap).slice(0, 6).forEach(([h, val]) => {
    doc.fillColor(INK).text(h, 40, hy, { width: 60, continued: false });
    doc.fillColor(MUTE).text(`Taxable ${inr(val.taxable)}  •  Tax ${inr(val.tax)}`, 100, hy);
    hy += 12;
  });

  doc.y = sy + 124;
  doc.fontSize(7.5).fillColor(MUTE).font('Helvetica')
    .text('Declaration: We declare that this invoice shows the actual price of the goods/services described and that all particulars are true and correct. e-Invoice registered on the Invoice Registration Portal; subject to GST rules.', 40, doc.y, { width: W - 80 });
  if (branding.terms) doc.moveDown(0.3).fontSize(7).fillColor(MUTE).text(`Terms & Conditions: ${branding.terms}`, 40, doc.y, { width: W - 80 });

  // Signature / stamp
  const sig = brandFile(branding, 'signatureFile'); const stamp = brandFile(branding, 'stampFile');
  if (sig || stamp) {
    const sy = Math.min(doc.y + 6, doc.page.height - 130);
    try { if (stamp) doc.image(stamp, W - 230, sy, { fit: [70, 50] }); } catch { /* */ }
    try { if (sig) doc.image(sig, W - 150, sy, { fit: [100, 50] }); } catch { /* */ }
    doc.fontSize(7).fillColor(MUTE).text('Authorised Signatory', W - 150, sy + 52, { width: 100, align: 'center' });
  }

  finalize(doc, rec.isCancelled ? `CANCELLED on ${dmy(rec.cancelDate)} (reason ${rec.cancelReasonCode}).` : null, branding);
  doc.end();
  return out;
}

// ── e-WAY BILL PDF ───────────────────────────────────────────────────────────
export async function ewbPdf(rec, branding = {}) {
  const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
  const out = toBuffer(doc);
  const W = doc.page.width;

  header(doc, 'e-WAY BILL', rec.ewbNo ? `EWB No: ${rec.ewbNo}` : 'Not yet generated', branding);
  watermark(doc, branding.watermark || (rec.isCancelled ? 'CANCELLED' : (rec.ewbNo ? '' : 'DRAFT')));

  // EWB + validity + QR strip
  const sy = doc.y;
  box(doc, 40, sy, W - 200, 64, '#eff6ff');
  doc.fontSize(7).fillColor(MUTE).font('Helvetica-Bold').text('EWB NUMBER', 48, sy + 7);
  doc.fontSize(13).fillColor(INK).font('Helvetica-Bold').text(rec.ewbNo || '— pending —', 48, sy + 18);
  doc.fontSize(7.5).font('Helvetica').fillColor(MUTE)
    .text(`Generated: `, 48, sy + 44, { continued: true }).fillColor(INK).text(rec.ewbDate ? dmy(rec.ewbDate) : '—')
    .fillColor(MUTE).text(`   Valid Upto: `, { continued: true }).fillColor(rec.validUpto && new Date(rec.validUpto) < new Date() ? '#dc2626' : INK).text(rec.validUpto ? dmy(rec.validUpto) : '—');

  if (rec.ewbNo) {
    try {
      const qr = await QRCode.toBuffer(`${rec.ewbNo}/${rec.fromGstin || ''}/${dmy(rec.docDate)}`, { margin: 0, width: 150 });
      box(doc, W - 150, sy, 110, 64, '#ffffff');
      doc.image(qr, W - 145, sy + 4, { width: 56, height: 56 });
      doc.fontSize(6).fillColor(MUTE).text('Scan', W - 84, sy + 26, { width: 34 });
    } catch { /* ignore */ }
  }
  doc.y = sy + 74;

  // Part A — document & supply
  const ay = doc.y;
  box(doc, 40, ay, W - 80, 70, '#f8fafc');
  doc.fontSize(8).fillColor(BRAND).font('Helvetica-Bold').text('PART A — Supply & Document', 48, ay + 6);
  doc.font('Helvetica').fontSize(8).fillColor(INK);
  const aLeft = [
    `Doc Type: ${rec.docType || '—'}`, `Doc No: ${rec.docNo || '—'}`, `Doc Date: ${dmy(rec.docDate)}`,
    `Supply: ${rec.supplyType === 'O' ? 'Outward' : 'Inward'}  Sub: ${rec.subSupplyType || '—'}`,
  ];
  const aRight = [
    `Txn Type: ${rec.transactionType || '—'}`, `Inv Value: ${inr(rec.totInvValue)}`,
    `Taxable: ${inr(rec.totalTaxable)}`, `Distance: ${rec.transDistance || 0} km`,
  ];
  doc.text(aLeft.join('\n'), 48, ay + 22, { width: (W - 96) / 2, lineGap: 2 });
  doc.text(aRight.join('\n'), 48 + (W - 96) / 2, ay + 22, { width: (W - 96) / 2, lineGap: 2 });
  doc.y = ay + 80;

  // From / To
  const py = doc.y;
  partyBlock(doc, 40, py, (W - 90) / 2, 'FROM (Dispatch)', { legalName: rec.fromTradeName, gstin: rec.fromGstin, addr1: rec.fromAddr1, location: rec.fromPlace, pincode: rec.fromPincode, stateCode: rec.fromStateCode });
  partyBlock(doc, 40 + (W - 90) / 2 + 10, py, (W - 90) / 2, 'TO (Ship To)', { legalName: rec.toTradeName, gstin: rec.toGstin, addr1: rec.toAddr1, location: rec.toPlace, pincode: rec.toPincode, stateCode: rec.toStateCode });
  doc.y = py + 100;

  // Part B — transport
  const by = doc.y;
  const partB = rec.partBReady || rec.vehicleNo || rec.transDocNo;
  box(doc, 40, by, W - 80, 64, partB ? '#f0fdf4' : '#fff7ed');
  doc.fontSize(8).fillColor(partB ? '#15803d' : '#b45309').font('Helvetica-Bold')
    .text(`PART B — Transport ${partB ? '(complete)' : '(pending)'}`, 48, by + 6);
  doc.font('Helvetica').fontSize(8).fillColor(INK);
  const modes = { 1: 'Road', 2: 'Rail', 3: 'Air', 4: 'Ship' };
  const bLeft = [
    `Mode: ${modes[rec.transMode] || '—'}`, `Vehicle No: ${rec.vehicleNo || '—'}`, `Vehicle Type: ${rec.vehicleType === 'O' ? 'ODC' : rec.vehicleType ? 'Regular' : '—'}`,
  ];
  const bRight = [
    `Transporter: ${rec.transporterName || '—'}`, `Transporter ID: ${rec.transporterId || '—'}`,
    `Trans Doc: ${rec.transDocNo || '—'} ${rec.transDocDate ? '(' + dmy(rec.transDocDate) + ')' : ''}`,
  ];
  doc.text(bLeft.join('\n'), 48, by + 22, { width: (W - 96) / 2, lineGap: 2 });
  doc.text(bRight.join('\n'), 48 + (W - 96) / 2, by + 22, { width: (W - 96) / 2, lineGap: 2 });
  doc.y = by + 74;

  // Items (paginated)
  const wm = branding.watermark || (rec.isCancelled ? 'CANCELLED' : (rec.ewbNo ? '' : 'DRAFT'));
  const drawHead = (ty) => {
    doc.rect(40, ty, W - 80, 16).fill(BRAND);
    doc.fillColor('#fff').fontSize(7.5).font('Helvetica-Bold');
    doc.text('Product', 46, ty + 4, { width: 230 });
    doc.text('HSN', 290, ty + 4, { width: 60 });
    doc.text('Qty', 360, ty + 4, { width: 60 });
    doc.text('Taxable', 430, ty + 4, { width: 120, align: 'right' });
    doc.font('Helvetica').fillColor(INK).fontSize(7.5);
    return ty + 16;
  };
  let ty = drawHead(doc.y);
  (rec.items || []).forEach((it, i) => {
    if (ty + 14 > CONTENT_BOTTOM(doc)) { doc.addPage(); watermark(doc, wm); ty = drawHead(contHeader(doc, branding, 'e-WAY BILL')); }
    if (i % 2) { doc.rect(40, ty, W - 80, 14).fill('#f8fafc'); doc.fillColor(INK); }
    doc.text(it.description || it.productName || '—', 46, ty + 3, { width: 230, ellipsis: true });
    doc.text(String(it.hsn || '—'), 290, ty + 3, { width: 60 });
    doc.text(`${it.quantity || ''} ${it.unit || ''}`, 360, ty + 3, { width: 60 });
    doc.text(inr(it.taxableAmount), 430, ty + 3, { width: 120, align: 'right' });
    ty += 14;
  });

  finalize(doc, rec.isCancelled ? `CANCELLED on ${dmy(rec.cancelDate)} (reason ${rec.cancelReasonCode}).` : (rec.isClosed ? 'CLOSED — delivery complete.' : 'Carry this e-way bill during the movement of goods.'), branding);
  doc.end();
  return out;
}
